<?php
/**
 * Migration Script for New Leaderboard API
 * 
 * This script helps migrate from the old multi-file API structure to the new
 * consolidated leaderboard-api.php file.
 * 
 * Run this once to:
 * 1. Test the new API functionality
 * 2. Backup old API files
 * 3. Verify database structure
 */

echo "🚀 Leaderboard API Migration Tool\n";
echo "==================================\n\n";

// Check if new API file exists
if (!file_exists('leaderboard-api.php')) {
    echo "❌ Error: leaderboard-api.php not found!\n";
    echo "   Make sure you've created the new consolidated API file.\n";
    exit(1);
}

echo "✅ New API file found: leaderboard-api.php\n";

// Test database connection
echo "🔍 Testing database connection...\n";

try {
    // Load config (same as in leaderboard-api.php)
    $config = [
        'db_host' => $_ENV['DB_HOST'] ?? 'localhost',
        'db_name' => $_ENV['DB_NAME'] ?? 'saasboomi_game',
        'db_user' => $_ENV['DB_USER'] ?? 'saasboomi_game',
        'db_pass' => $_ENV['DB_PASS'] ?? 'JCO]hB2rMrSuhqK(',
    ];
    
    $dsn = "mysql:host={$config['db_host']};dbname={$config['db_name']};charset=utf8mb4";
    $pdo = new PDO($dsn, $config['db_user'], $config['db_pass']);
    echo "✅ Database connection successful\n";
    
    // Check if table exists and has data
    $stmt = $pdo->query("SELECT COUNT(*) as count FROM leaderboard");
    $count = $stmt->fetch()['count'];
    echo "📊 Found {$count} existing scores in database\n";
    
} catch (PDOException $e) {
    echo "❌ Database connection failed: " . $e->getMessage() . "\n";
    echo "   Please check your database credentials in the API file.\n";
    exit(1);
}

// Test API endpoints
echo "\n🧪 Testing API endpoints...\n";

$apiUrl = 'http://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI']) . '/leaderboard-api.php';

// Test leaderboard endpoint
echo "   Testing leaderboard endpoint... ";
$response = file_get_contents($apiUrl . '?action=leaderboard');
$data = json_decode($response, true);
if ($data && $data['success']) {
    echo "✅ OK (" . count($data['data']) . " scores)\n";
} else {
    echo "❌ Failed\n";
}

// Test top-player endpoint
echo "   Testing top-player endpoint... ";
$response = file_get_contents($apiUrl . '?action=top-player');
$data = json_decode($response, true);
if ($data && $data['success']) {
    echo "✅ OK (Top score: " . ($data['data']['top_score'] ?? 0) . ")\n";
} else {
    echo "❌ Failed\n";
}

// Test stats endpoint
echo "   Testing stats endpoint... ";
$response = file_get_contents($apiUrl . '?action=stats');
$data = json_decode($response, true);
if ($data && $data['success']) {
    echo "✅ OK (Total: " . $data['data']['total_scores'] . " scores)\n";
} else {
    echo "❌ Failed\n";
}

// Backup old files
echo "\n📦 Creating backup of old API files...\n";

$oldFiles = ['db.php', 'create-table.php', 'submit-score.php', 'top-scores.php', 'get-top-player.php'];
$backupDir = 'backup_' . date('Y-m-d_H-i-s');

if (!is_dir($backupDir)) {
    mkdir($backupDir, 0755, true);
    echo "   Created backup directory: {$backupDir}/\n";
}

foreach ($oldFiles as $file) {
    if (file_exists($file)) {
        if (copy($file, $backupDir . '/' . $file)) {
            echo "   ✅ Backed up: {$file}\n";
        } else {
            echo "   ❌ Failed to backup: {$file}\n";
        }
    } else {
        echo "   ⚠️  File not found: {$file}\n";
    }
}

// Generate .env file if it doesn't exist
if (!file_exists('.env')) {
    echo "\n📝 Creating .env file...\n";
    
    $envContent = "# Leaderboard API Configuration
# Generated by migration script

# Database Configuration
DB_HOST=localhost
DB_NAME=saasboomi_game
DB_USER=saasboomi_game
DB_PASS=JCO]hB2rMrSuhqK(

# API Configuration
MAX_SCORES=10
RATE_LIMIT=60
MAX_NAME_LENGTH=50
MAX_SCORE=999999
";
    
    if (file_put_contents('.env', $envContent)) {
        echo "   ✅ Created .env file with current settings\n";
        echo "   ⚠️  Please review and update the database password!\n";
    } else {
        echo "   ❌ Failed to create .env file\n";
    }
}

// Migration summary
echo "\n🎉 Migration Summary\n";
echo "===================\n";
echo "✅ New consolidated API is ready at: leaderboard-api.php\n";
echo "✅ Database connection tested successfully\n";
echo "✅ All API endpoints are functional\n";
echo "✅ Old files backed up to: {$backupDir}/\n";

if (file_exists('.env')) {
    echo "✅ Environment configuration created\n";
}

echo "\n📋 Next Steps:\n";
echo "1. Update your frontend code to use the new API endpoints\n";
echo "2. Test the game with the new API\n";
echo "3. Update any external integrations\n";
echo "4. Consider removing old API files after testing\n";
echo "5. Set up proper environment variables in production\n";

echo "\n🔗 New API endpoints:\n";
echo "   POST {$apiUrl}?action=submit\n";
echo "   GET  {$apiUrl}?action=leaderboard\n";
echo "   GET  {$apiUrl}?action=top-player\n";
echo "   GET  {$apiUrl}?action=stats\n";

echo "\n✨ Migration completed successfully!\n";
?>